### PR TITLE
Brings everything uptodate with bc-csharp

### PR DESCRIPTION
**Pull request by peterdettman**
Any PORTABLE-specific code I've found in BouncyCastle-PCL has been added to bc-csharp under PORTABLE flags, and merged back in this PR.

The tests in crypto.tests.Net45 still pass. The NAnt build run in BouncyCastle-PCL now compiles cleanly, but there are at least a couple of test failures, which I need to chase up next.

### CODE REVIEW

**Comment by peterdettman** [comment]
Pushed some more changes, the trees are almost synced up and the NAnt build now passes, so almost home!

The remaining differences are:
- DOTNET and LIB preprocessor flags - these are used in BouncyCastle-PCL, but what do they signify?
- AssemblyInfo.cs has slightly different AssemblyVersion in -PCL, also has AssemblyFileVersion and AssemblyInformationalVersion, which are absent in original library; arguments for which we should be using?
- I haven't added the new project files to bc-csharp yet, so that's a difference, just for completeness.

**Comment by peterdettman** [comment]
Also, I don't understand why AppVeyor complained!

**Comment by clairernovotny** [comment]
I'll take a look later tonight or tomorrow...as to AppVeyor, I just hit Re-build PR and it was fine. I suspect network flakiness on restore or something.

The different AssemblyInfo stuff is for the following reasons:

AssemblyVersion: Used for strong naming. Can be hard to change without binding redirects
AssemblyFileVersion: Usually used to indicate a patched/updated version of an assembly without updating the AssemblyVersion. This minimizes binding redirects while still providing a difference
AssemblyInformationalVersion: This doesn't have to be a 0.0.0.0 string like the other two. In this case, I'm using GitVersion to stamp the full SemVer, including branch and commit SHA. It helps provide traceability to the exact build a file came from.

As to LIB, I forget, I'll look when I do the PR/merge.

DOTNET is for the "modern PCL" Standard Platform 1.3 stuff. This should explain it better: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md.

Very soon, `dotnet` should go away and be replaced by `netstandard1.3`. We just need the tooling support but it'll greatly simplify this PCL.

**Comment by clairernovotny** [comment]
should I merge this in yet? [edited: scratch that, just did the merge as it's easy enough to keep it updated as needed]

**Comment by peterdettman** [comment]
Should be fine, I might push some final commits here so leave open? Do you have any thoughts on LIB?

**Comment by clairernovotny** [comment]
looking now, yeah we can keep this open, though not sure how GitHub treats it -- if it re-opens if more commits are pushed to the branch or if a new PR is needed?

**Comment by peterdettman** [comment]
We'll cross that bridge when we come to it I guess!

**Comment by clairernovotny** [comment]
Ok, now I remember... it has to do with the way the tests are run. All of the tests had a bunch of Main methods. LIB was used to comment out the Main's there and then the corresponding AllTests. I think this is an artifact of the way NUnit used to run? The current way with Test Adapters doesn't seem to need the Main methods or AllTests. I could be wrong though and totally missing something.

**Comment by peterdettman** [comment]
Ah, OK, yeah, in the old VS solution there's a separate project that runs many of the tests via their Main method. I think we can just add the DOTNET and LIB flags safely enough then.

**Pull request merged**
